#!/bin/bash
#
# Autonomous AI Coding & Verification Pipeline using Glupe
#
# This script automates the process of Test-Driven Architecture (TDA).
# It audits an implementation file against a specification, and if divergences
# are found, it uses the audit report as feedback to trigger an auto-healing
# loop, forcing the AI to correct its own mistakes.
#

# --- Configuration ---
set -e # Exit immediately if a command exits with a non-zero status.

# The master architectural specification. This is the source of truth.
SPEC_FILE="spec.glp"
# The source code file that the AI is working on.
IMPLEMENTATION_FILE="main.cpp"
# The refined blueprint of the implementation, generated on-the-fly.
REFINED_IMPL_FILE="${IMPLEMENTATION_FILE}.glp"
# The JSON report file generated by the audit.
REPORT_FILE="report.json"
# Maximum number of self-healing attempts before failing the pipeline.
MAX_HEAL_ATTEMPTS=3

# --- Helper Functions ---
info() {
    echo "[INFO] $1"
}

warn() {
    echo "[WARN] $1"
}

fail() {
    echo "[FAIL] $1" >&2
    exit 1
}

# --- Pre-flight Checks ---
if ! command -v glupe &> /dev/null; then
    fail "Glupe is not installed or not in the system's PATH."
fi

if ! command -v jq &> /dev/null; then
    fail "jq is not installed. It is required to parse the audit report."
fi

if [ ! -f "$SPEC_FILE" ]; then
    fail "Specification file not found: $SPEC_FILE"
fi

if [ ! -f "$IMPLEMENTATION_FILE" ]; then
    fail "Implementation file not found: $IMPLEMENTATION_FILE"
fi

# --- Main Pipeline ---
info "Starting Autonomous AI Coding Pipeline..."

for i in $(seq 1 $MAX_HEAL_ATTEMPTS); do
    info "--- Cycle $i/$MAX_HEAL_ATTEMPTS ---"

    info "Refining '$IMPLEMENTATION_FILE' into '$REFINED_IMPL_FILE'..."
    glupe "$IMPLEMENTATION_FILE" -refine -local

    info "Auditing implementation against spec..."
    if glupe audit "$SPEC_FILE" "$REFINED_IMPL_FILE" --output "$REPORT_FILE" --ignore-scaffold -local; then
        info "✅ Audit PASSED. Implementation strictly matches specification."
        exit 0
    else
        warn "Audit FAILED. Implementation diverges from specification. Attempting to auto-heal..."
    fi

    if [ "$i" -eq "$MAX_HEAL_ATTEMPTS" ]; then
        break
    fi

    info "Analyzing audit report '$REPORT_FILE'..."
    MISSING_COUNT=$(jq '.missing | length' "$REPORT_FILE")
    HALLUCINATED_COUNT=$(jq '.hallucinated | length' "$REPORT_FILE")

    HEAL_COMMAND="glupe \"$IMPLEMENTATION_FILE\" -fill --feedback \"$REPORT_FILE\" -local"
    if [ "$MISSING_COUNT" -gt 0 ] || [ "$HALLUCINATED_COUNT" -gt 0 ]; then
        warn "Structural divergence detected. Upgrading to global update (-u) to fix architecture."
        HEAL_COMMAND="glupe \"$IMPLEMENTATION_FILE\" -u --feedback \"$REPORT_FILE\" -local"
    fi

    info "Executing auto-heal pass..."
    eval "$HEAL_COMMAND"
done

fail "Pipeline failed. Could not bring implementation into compliance after $MAX_HEAL_ATTEMPTS attempts."